name: Node-CI-workflow

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    Node-CI:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v5
              with:
                node-version: '22'
            - name: Install dependencies
              run: npm ci   # Creates a clean install of dependencies based on package-lock.json
            - name: Check voulnerabilities
              run: npm audit --audit-level=high
            - name: Linting
              run: npm run lint
            - name: Run tests
              run: npm run test
            - name: Build project
              run: npm run build
            - name: Render deployment
              env:
                deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
              run: |
                curl "$deploy_url"
